feat: add input to allow specifying the asset name rather than calc it from the repository name

diff --git a/.github/workflows/patch-font.yml b/.github/workflows/patch-font.yml
--- a/.github/workflows/patch-font.yml
+++ b/.github/workflows/patch-font.yml
@@ -1,6 +1,11 @@
 name: "Patch Iosevka"
 on:
   workflow_call:
+    inputs:
+      asset_name:
+        description: 'The font variant name'
+        required: false
+        type: string
 
 permissions:
   contents: write
@@ -18,12 +23,26 @@ defaults:
     shell: bash
 
 jobs:
+  calc_asset_name:
+    runs-on: ubuntu-latest
+    outputs:
+      asset_name: ${{ steps.calc.outputs.asset_name }}
+    steps:
+      - name: Forward given asset name or calculate it with repository variables
+        id: calc
+        run: |
+          if [ -n "${{ inputs.asset_name }}" ]; then
+            echo "asset_name=${{ inputs.asset_name }}" >> "${GITHUB_OUTPUT}"
+          else
+            echo "asset_name=${GITHUB_REPOSITORY#"${GITHUB_REPOSITORY_OWNER}/"}" >> "${GITHUB_OUTPUT}"
+            echo "asset_name=$(grep 'asset_name=' ${GITHUB_OUTPUT})"
+          fi
+
   check:
     runs-on: ubuntu-latest
     outputs:
       needs_patch: ${{ steps.version-check.outputs.needs_patch }}
       release_tag: ${{ steps.version-check.outputs.release_tag }}
-      asset_name: ${{ steps.version-check.outputs.asset_name }}
     steps:
       - name: Create work dir
         run: mkdir -p ${{ env.WORK_DIR }}
@@ -55,8 +74,6 @@ jobs:
             exit 0
           fi
           echo "needs_patch=true" >> "${GITHUB_OUTPUT}"
-          echo "asset_name=${GITHUB_REPOSITORY#"${GITHUB_REPOSITORY_OWNER}/"}" >> "${GITHUB_OUTPUT}"
-          echo "asset_name=$(grep 'asset_name=' ${GITHUB_OUTPUT})"
 
   setup_tools:
     needs: check
@@ -102,7 +119,7 @@ jobs:
           path: ${{ env.WORK_DIR }}/${{ env.FONT_PATCHER_SCRIPT }}
 
   patch:
-    needs: [check, setup_tools]
+    needs: [calc_asset_name, check, setup_tools]
     if: ${{ needs.check.outputs.needs_patch }}
     runs-on: ubuntu-latest
     steps:
@@ -130,35 +147,35 @@ jobs:
             -H "Accept: application/vnd.github+json" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
             https://api.github.com/repos/be5invis/Iosevka/releases/tags/${{ needs.check.outputs.release_tag }} | \
-            eval 'jq -r ".assets | map(select(.name | test(\"PkgTTF-${{ needs.check.outputs.asset_name }}-${IOSEVKA_VERSION}\\\\.zip\"))) | .[0].url"'
+            eval 'jq -r ".assets | map(select(.name | test(\"PkgTTF-${{ needs.calc_asset_name.outputs.asset_name }}-${IOSEVKA_VERSION}\\\\.zip\"))) | .[0].url"'
           )"
           echo "ASSET_URL=${ASSET_URL}"
           if [ "${ASSET_URL}" == "null" ] ; then
-            echo "Asset 'PkgTTF-${{ needs.check.outputs.asset_name }}-${IOSEVKA_VERSION}.zip' not found" >&2
+            echo "Asset 'PkgTTF-${{ needs.calc_asset_name.outputs.asset_name }}-${IOSEVKA_VERSION}.zip' not found" >&2
             exit 1
           fi
           curl -fsSL \
             -H "Accept: application/octet-stream" \
             -H "X-GitHub-Api-Version: 2022-11-28" \
-            -o "${{ env.BASE_INPUT_DIR }}/${{ needs.check.outputs.asset_name }}.zip" \
+            -o "${{ env.BASE_INPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}.zip" \
             "${ASSET_URL}"
-          unzip -o "${{ env.BASE_INPUT_DIR }}/${{ needs.check.outputs.asset_name }}.zip" -d "${{ env.BASE_INPUT_DIR }}/${{ needs.check.outputs.asset_name }}"
+          unzip -o "${{ env.BASE_INPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}.zip" -d "${{ env.BASE_INPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}"
       - name: Patch fonts
         run: |
-          echo "Patching ${{ needs.check.outputs.asset_name }} into ${{ env.BASE_OUTPUT_DIR }}/${{ needs.check.outputs.asset_name }}"
-          mkdir -p "${{ env.BASE_OUTPUT_DIR }}/${{ needs.check.outputs.asset_name }}"
-          find "${{ env.BASE_INPUT_DIR }}/${{ needs.check.outputs.asset_name }}" -type f | \
-          parallel echo "Patching {}" \; "${GITHUB_WORKSPACE}/${{ env.FONTFORGE_NAME }}" -script "${GITHUB_WORKSPACE}/font-patcher" "{}" --quiet --no-progressbars --complete -out "${{ env.BASE_OUTPUT_DIR }}/${{ needs.check.outputs.asset_name }}"
+          echo "Patching ${{ needs.calc_asset_name.outputs.asset_name }} into ${{ env.BASE_OUTPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}"
+          mkdir -p "${{ env.BASE_OUTPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}"
+          find "${{ env.BASE_INPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}" -type f | \
+          parallel echo "Patching {}" \; "${GITHUB_WORKSPACE}/${{ env.FONTFORGE_NAME }}" -script "${GITHUB_WORKSPACE}/font-patcher" "{}" --quiet --no-progressbars --complete -out "${{ env.BASE_OUTPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}"
       - name: Share output
         uses: actions/upload-artifact@v4
         with:
-          name: ${{ needs.check.outputs.asset_name }}
-          path: ${{ env.BASE_OUTPUT_DIR }}/${{ needs.check.outputs.asset_name }}
+          name: ${{ needs.calc_asset_name.outputs.asset_name }}
+          path: ${{ env.BASE_OUTPUT_DIR }}/${{ needs.calc_asset_name.outputs.asset_name }}
           retention-days: 1
 
   commit:
     runs-on: ubuntu-latest
-    needs: [check, patch]
+    needs: [check, calc_asset_name, patch]
     if: ${{ needs.check.outputs.needs_patch }}
     steps:
       - name: Remove temporary artifacts
@@ -182,5 +199,5 @@ jobs:
         run: |
           git add --all
           git commit -m "chore: update patched fonts"
-          git tag "${{ needs.check.outputs.release_tag }}" -m "Patched ${{ needs.check.outputs.asset_name }} ${{ needs.check.outputs.release_tag }}"
+          git tag "${{ needs.check.outputs.release_tag }}" -m "Patched ${{ needs.calc_asset_name.outputs.asset_name }} ${{ needs.check.outputs.release_tag }}"
           git push --follow-tags
